name: Update feed
on:
  schedule:
    # This will run every ten minutes. Alter it using https://crontab.guru/.
    - cron: '*/10 * * * *'  
  workflow_dispatch:
jobs:
  rss-to-mastodon:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v8
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/mastofeedbot
          key: mastodon-feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: mastodon-feed-cache-
      - name: GitHub
        uses: 'joschi/mastofeedbot@v0.2.0'
        with:
          rss-feed: 'https://github.blog/changelog/feed/'
          # Visibility of the posted status (public | unlisted | private | direct)
          status-visibility: unlisted
          dry-run: false
          template: |
            {{{item.title}}}

            {{{item.link}}}
          api-endpoint: 'https://mastodon.bot/'
          api-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          cache-file: ${{ github.workspace }}/mastofeedbot/cache.json
          cache-limit: 1000
          initial-post-limit: 0
  rss-to-bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v8
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/blueskyfeedbot
          key: bluesky-feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: bluesky-feed-cache-
      - name: Post to Bluesky
        uses: 'joschi/blueskyfeedbot@v0.0.4'
        with:
          rss-feed: 'https://github.blog/changelog/feed/'
          dry-run: false
          template: |
            {{{item.title}}}

            {{{item.link}}}
          username: ${{ secrets.BLUESKY_USERNAME }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          cache-file: ${{ github.workspace }}/blueskyfeedbot/cache.json
          cache-limit: 1000
          initial-post-limit: 0
